import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--record_dir', type=str, default='./datasets/blister_pack_RTT/datas/tfrecords/')
parser.add_argument('--feature_dir', type=str, default='./datasets/blister_pack_RTT/features/')
parser.add_argument('--model_dir', type=str, default='./checkpoint/model/')
parser.add_argument('--pre_model', type=str, default='')
parser.add_argument('--restore_model', type=str, default='./checkpoint/model/190429_192350/model.ckpt-98')
parser.add_argument('--dataset', type=str, default='blister_pack_RTT')
parser.add_argument('--batch_size', type=int, default=1)
parser.add_argument('--total_epochs', type=int, default=100)
parser.add_argument('--reduction_ratio', type=int, default=4)
parser.add_argument('--learning_rate', type=float, default=0.001)  # 0.001
parser.add_argument('--weight_decay', type=float, default=0.0005)
parser.add_argument('--momentum', type=float, default=0.9)
parser.add_argument('--drop_rate', type=float, default=0.5)
parser.add_argument('--part', type=bool, default=True)
parser.add_argument('--all', type=bool, default=True)
parser.add_argument('--half', type=bool, default=False)
parser.add_argument('--straight', type=bool, default=False)
parser.add_argument('--only_test', type=bool, default=True)
parser.add_argument('--load_model', type=bool, default=True)
parser.add_argument('--feat_ext', type=bool, default=True)
parser.add_argument('--normalize_feat', type=bool, default=True)
parser.add_argument('--rerank', type=bool, default=True)
IFPA_args = parser.parse_args()